// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaLocadora.Data;

#nullable disable

namespace SistemaLocadora.Migrations
{
    [DbContext(typeof(LocadoraContext))]
    partial class LocadoraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaLocadora.Models.ClienteModel", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CPF");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Rg")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("RG");

                    b.Property<string>("Sobrenome")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("SistemaLocadora.Models.LocacaoModel", b =>
                {
                    b.Property<int>("IdLocacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Locacao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocacao"));

                    b.Property<DateOnly?>("DataLocacao")
                        .HasColumnType("date")
                        .HasColumnName("Data_Locacao");

                    b.Property<int?>("Dias")
                        .HasColumnType("int");

                    b.Property<int?>("FkClienteIdCliente")
                        .HasColumnType("int")
                        .HasColumnName("fk_Cliente_Id_Cliente");

                    b.Property<int?>("FkVeiculoIdVeiculo")
                        .HasColumnType("int")
                        .HasColumnName("fk_Veiculo_Id_Veiculo");

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("int");

                    b.Property<double?>("Valor")
                        .HasColumnType("float");

                    b.HasKey("IdLocacao");

                    b.HasIndex("FkClienteIdCliente");

                    b.HasIndex("FkVeiculoIdVeiculo");

                    b.ToTable("Locacao", (string)null);
                });

            modelBuilder.Entity("SistemaLocadora.Models.VeiculoModel", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Veiculo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVeiculo"));

                    b.Property<int?>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Marca")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Placa")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("ValorDeCompra")
                        .HasColumnType("float")
                        .HasColumnName("Valor_de_Compra");

                    b.Property<double?>("ValorDiaria")
                        .HasColumnType("float")
                        .HasColumnName("Valor_Diaria");

                    b.HasKey("IdVeiculo");

                    b.ToTable("Veiculo", (string)null);
                });

            modelBuilder.Entity("SistemaLocadora.Models.VendaModel", b =>
                {
                    b.Property<int>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Venda");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenda"));

                    b.Property<DateOnly?>("DataVenda")
                        .HasColumnType("date")
                        .HasColumnName("Data_Venda");

                    b.Property<int?>("FkVeiculoIdVeiculo")
                        .HasColumnType("int")
                        .HasColumnName("fk_Veiculo_Id_Veiculo");

                    b.Property<double?>("ValorDeVenda")
                        .HasColumnType("float")
                        .HasColumnName("Valor_Venda");

                    b.HasKey("IdVenda");

                    b.HasIndex("FkVeiculoIdVeiculo");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("SistemaLocadora.Models.LocacaoModel", b =>
                {
                    b.HasOne("SistemaLocadora.Models.ClienteModel", "Cliente")
                        .WithMany("Locacaos")
                        .HasForeignKey("FkClienteIdCliente")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Locacao_2");

                    b.HasOne("SistemaLocadora.Models.VeiculoModel", "Veiculo")
                        .WithMany("Locacaos")
                        .HasForeignKey("FkVeiculoIdVeiculo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Locacao_3");

                    b.Navigation("Cliente");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SistemaLocadora.Models.VendaModel", b =>
                {
                    b.HasOne("SistemaLocadora.Models.VeiculoModel", "Veiculo")
                        .WithMany("Venda")
                        .HasForeignKey("FkVeiculoIdVeiculo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Venda_3");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SistemaLocadora.Models.ClienteModel", b =>
                {
                    b.Navigation("Locacaos");
                });

            modelBuilder.Entity("SistemaLocadora.Models.VeiculoModel", b =>
                {
                    b.Navigation("Locacaos");

                    b.Navigation("Venda");
                });
#pragma warning restore 612, 618
        }
    }
}
